=== ksonda/usgs-sta-pygeoapi/chyld-pilot/schemas/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 sp1 (x64) (http://www.altova.com) by Eric Boisvert (Natural Resources Canada) -->
<xs:schema xmlns:p="urn:x-gsip:1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:x-gsip:1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="data" type="p:DataType">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="MatchType">
		<xs:sequence>
			<xs:element name="mime-type" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string"/>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="source">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="useAnonFtp" type="xs:boolean" default="false"/>
							<xs:attribute name="alt-media-type" type="xs:string"/>
							<xs:attribute name="proxy" type="xs:boolean" default="false"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="pattern" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="DataType">
		<xs:sequence>
			<xs:element name="match" type="p:MatchType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== ksonda/usgs-sta-pygeoapi/chyld-pilot/data/waterbody.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:data xmlns:p="urn:x-gsip:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:x-gsip:1.0 file:///C:/java64_8/gsip/WebContent/schemas/data.xsd">
	<!--  each elements are parsed into p1 to p{n}.  p0 = "data/x/y/z.." -->
	<p:match pattern="waterbody/CGNDB/CGNDB/CGNDB/.*">
		<p:mime-type>text/html</p:mime-type>
		<!--  can have more -->
		<p:source>http://www4.rncan.gc.ca/search-place-names/unique?id=${p5}</p:source>
	</p:match>
	<p:match pattern="waterbody/CGNDB/CGNDB/CGNDB/.*">
		<p:mime-type>application/json</p:mime-type>
		<!--  can have more -->
		<p:source proxy="true">http://geogratis.gc.ca/services/geoname/en/features/${p5}.json</p:source>
	</p:match>
	<p:match pattern="waterbody/CGNDB/CGNDB/CGNDB/.*">
		<p:mime-type>application/vnd.google-earth.kml+xml</p:mime-type>
		<!--  can have more -->
		<p:source proxy="true">http://geogratis.gc.ca/services/geoname/en/features/${p5}.kml</p:source>
	</p:match>
	
	<!--  CHyF representations -->
	<p:match pattern="waterbody/CHYF/CHYF/CHYF/.*">
		<p:mime-type>text/html</p:mime-type>
		<!--  can have more -->
		<p:source>http://chyf.ca/chyf/eflowpath/filter.html?property=nameID&amp;predicate=equals&amp;value=${p5}</p:source>
	</p:match>
	<p:match pattern="waterbody/CHYF/CHYF/CHYF/.*">
		<p:mime-type>application/vnd.geo+json</p:mime-type>
		<!--  can have more -->
		<p:source proxy="true">http://chyf.ca/chyf/eflowpath/filter.json?property=nameID&amp;predicate=equals&amp;value=${p5}</p:source>
	</p:match>
	<!--  by position  -->
	<p:match pattern="waterbody/CHYF/POS/CHYF/.*">
		<p:mime-type>text/html</p:mime-type>
		<!--  can have more -->
		<p:source>http://chyf.ca/chyf/ecatchment/upstreamOf.html?point=${p5}</p:source>
	</p:match>
     <p:match pattern="waterbody/CHYF/POS/CHYF/.*">
		<p:mime-type>application/vnd.geo+json</p:mime-type>
		<p:source proxy="true">http://chyf.ca/chyf/ecatchment/upstreamOf.json?point=${p5}</p:source>
	</p:match>
	

</p:data>

=== ksonda/usgs-sta-pygeoapi/chyld-pilot/data/node.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:data xmlns:p="urn:x-gsip:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:x-gsip:1.0 file:///C:/java64_8/gsip/WebContent/schemas/data.xsd">
	<!--  each elements are parsed into p1 to p{n}.  p0 = "data/x/y/z.." -->
	<p:match pattern="node/.*">
		<p:mime-type>application/x-turtle</p:mime-type>
		<p:source>${gsip}/node/${p2}?f=ttl</p:source>
	</p:match>
		<p:match pattern="node/.*">
		<p:mime-type>application/ld+json</p:mime-type>
		<p:source>${gsip}/node/${p2}?f=jsonld</p:source>
	</p:match>
		<p:match pattern="node/.*">
		<p:mime-type>application/rdf+xml</p:mime-type>
		<p:source>${gsip}/node/${p2}?f=rdf</p:source>
	</p:match>
</p:data>

=== ksonda/usgs-sta-pygeoapi/chyld-pilot/data/gwmonitoring.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:data xmlns:p="urn:x-gsip:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:x-gsip:1.0 file:///C:/java64_8/gsip/WebContent/schemas/data.xsd">
	<!--  each elements are parsed into p1 to p{n}.  p0 = "data/x/y/z.." -->
	<p:match pattern="gwmon/WML2/historical/GIN/.*">
		<p:mime-type>text/plain</p:mime-type>
		<!--  can have more -->
		<p:source>http://gin.gw-info.net/service/gin/highcharts/data/en/0db46343-1c4f-aefc-1227-a6a90d49d53c/${p5}.zip?datasource=</p:source>
	</p:match>
	
	<p:match pattern="gwmon/WML2/historical/GIN/.*">
		<p:mime-type>text/xml</p:mime-type>
		<!--  can have more -->
		<p:source>http://gin.gw-info.net/GinService/sos/gw?REQUEST=GetFeatureOfInterest&amp;VERSION=2.0.0&amp;SERVICE=SOS&amp;featureOfInterest=${p5}</p:source>
	</p:match>
	
	
	<p:match pattern="gwmon/WML2/historical/GIN/.*">
		<p:mime-type>application/vnd.geo+json</p:mime-type>
		<!--  can have more -->
		<p:source proxy="true">http://gin.gw-info.net/service/ngwds/en/data/geojson/monitoring/${p5}</p:source>
	</p:match>
	
		<p:match pattern="gwmon/WML2/historical/GIN/.*">
		<p:mime-type>text/html</p:mime-type>
		<!--  can have more -->
		<p:source>http://gin.gw-info.net/service/gin/sos2/timeseries/natres?ID=${p5}</p:source>
	</p:match>
	
</p:data>

=== ksonda/usgs-sta-pygeoapi/chyld-pilot/data/waterwell.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:data xmlns:p="urn:x-gsip:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:x-gsip:1.0 file:///C:/java64_8/gsip/WebContent/schemas/data.xsd">
	<!--  each elements are parsed into p1 to p{n}.  p0 = "data/x/y/z.." -->
	<p:match pattern="gwml/gwml1/gsip/gin/qc\..*">
		<p:mime-type>text/html</p:mime-type>
		<!--  can have more -->
		<p:source>http://gin.gw-info.net/service/api_ngwds:gin2/en/waterMLData/index.html?PROFILE=gin&amp;REQUEST=GetFeature&amp;INFO_FORMAT=text/html&amp;FID=${p5?replace("qc.","urn.ngwd.qc.mef.well_")}&amp;LOCALE=en</p:source>
	</p:match>
	<p:match pattern="gwml/gwml1/gsip/gin/qc\..*">
		<p:mime-type>text/xml</p:mime-type>
		<p:source>http://gin.gw-info.net/service/gin/wfs/gin?REQUEST=GetFeature&amp;INFO_FORMAT=xml&amp;FID=${p5?replace("qc.","urn.ngwd.qc.mef.well_")}</p:source>
	</p:match>
	<p:match pattern="gwml/gwml1/gsip/gin/qc\..*">
		<p:mime-type>application/vnd.geo+json</p:mime-type>
		<p:source proxy="true">http://gin.gw-info.net/service/ngwds/en/data/geojson/wells?URL=https://geoconnex.ca/id/waterwells/${p5}</p:source>
	</p:match>
</p:data>

=== ksonda/usgs-sta-pygeoapi/chyld-pilot/data/bedrock.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:data xmlns:p="urn:x-gsip:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:x-gsip:1.0 file:///C:/java64_8/gsip/WebContent/schemas/data.xsd">
	<!--  each elements are parsed into p1 to p{n}.  p0 = "data/x/y/z.." -->
	<p:match pattern="dataset/gin/gin/GIN/gin-.*">
		<p:mime-type>text/html</p:mime-type>
		<!--  can have more -->
		<p:source alt-media-type="text/html">http://gin.gw-info.net/service/api_ngwds:gin2/en/data/standard.download.html?id=${p5?replace("gin-","")}</p:source>
	</p:match>
	<p:match pattern="dataset/gin/gin/GIN/gin-.*">
		<p:mime-type>application/vnd.geo+json</p:mime-type>
		<p:source>http://gin.gw-info.net/SpatialConversionEngine/gw_data/get/${p5?replace("gin-","")}?f=GeoJSON</p:source>
	</p:match>
	<p:match pattern="dataset/gin/gin/GIN/gin-.*">
		<p:mime-type>application/vnd.google-earth.kml+xml</p:mime-type>
		<p:source>http://gin.gw-info.net/SpatialConversionEngine/gw_data/get/${p5?replace("gin-","")}?f=KML</p:source>
	</p:match>
	<p:match pattern="dataset/gin/gin/GIN/gin-.*">
		<p:mime-type>application/x-esri-shape</p:mime-type>
		<p:source>http://gin.gw-info.net/SpatialConversionEngine/gw_data/get/${p5?replace("gin-","")}?f=ESRI%20Shapefile</p:source>
	</p:match>

</p:data>

=== ksonda/usgs-sta-pygeoapi/chyld-pilot/data/weblex.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:data xmlns:p="urn:x-gsip:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:x-gsip:1.0 file:///C:/java64_8/gsip/WebContent/schemas/data.xsd">
	<!--  each elements are parsed into p1 to p{n}.  p0 = "data/x/y/z.." -->
	<p:match pattern="weblex/gsc/weblex/.*/.*">
		<p:mime-type>text/html</p:mime-type>
		<p:source>https://weblex.nrcan.gc.ca/html/${p4}/${p5}.html</p:source>
	</p:match>
	<p:match pattern="weblex/gsc/weblex/.*/.*">
		<p:mime-type>application/json</p:mime-type>
		<p:source>https://weblex.nrcan.gc.ca/ws/lexrest.svc/lithobyid/${p5}.json</p:source>
	</p:match>
	<p:match pattern="weblex/gsc/weblex/.*/.*">
		<p:mime-type>text/xml</p:mime-type>
		<p:source>https://weblex.nrcan.gc.ca/ws/lexrest.svc/lithobyid/${p5}.xml</p:source>
	</p:match>


</p:data>

=== ksonda/usgs-sta-pygeoapi/chyld-pilot/data/swmonitoring.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:data xmlns:p="urn:x-gsip:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:x-gsip:1.0 file:///C:/java64_8/gsip/WebContent/schemas/data.xsd">
	<!--  each elements are parsed into p1 to p{n}.  p0 = "data/x/y/z.." -->
	<p:match pattern="swmonitoring/WML2/real_time/MDDELCC/.*">
		<p:mime-type>text/html</p:mime-type>
		<p:source>https://www.cehq.gouv.qc.ca/suivihydro/graphique.asp?NoStation=${p5?replace("MDDELCC_","")}</p:source>
	</p:match>
	<p:match pattern="swmonitoring/WML2/real_time/MDDELCC/.*">
		<p:mime-type>text/plain</p:mime-type>
		<!--  can have more -->
		<p:source>https://www.cehq.gouv.qc.ca/suivihydro/fichier_donnees.asp?NoStation=${p5?replace("MDDELCC_","")}</p:source>
	</p:match>
	<p:match pattern="swmonitoring/WML2/historical/MDDELCC/.*">
		<p:mime-type>text/plain</p:mime-type>
		<!--  can have more -->
		<p:source>https://www.cehq.gouv.qc.ca/depot/historique_donnees/fichier/${p5?replace("MDDELCC_","")}_Q.txt</p:source>
	</p:match>
	<!--  CHyF representations -->
	<p:match pattern="swmonitoring/WML2/historical/MDDELCC/.*">
		<p:mime-type>application/vnd.geo+json</p:mime-type>
		<!--  can have more -->
		<p:source proxy="true" useAnonFtp="true">ftp://ftp.cits.rncan.gc.ca/pub/hydro/GeEau/tests/gsip/prod/${p5?replace("MDDELCC_","")}.json</p:source>
	</p:match>
	
	<!--  federal  -->
	
	<p:match pattern="swmonitoring/WML2/historical/WSC/.*">
		<p:mime-type>text/html</p:mime-type>
		<!--  can have more -->
		<p:source>https://wateroffice.ec.gc.ca/report/historical_e.html?stn=${p5?replace("WSC_","")}</p:source>
	</p:match>
	
	<p:match pattern="swmonitoring/WML2/historical/WSC/.*">
		<p:mime-type>application/vnd.geo+json</p:mime-type>
		<!--  replace the username and password accordingly, -->
		<p:source proxy="true">ftp://USER:PASSWORD@nais.ec.gc.ca/TimeSeries/${p5?replace("WSC_","")}.json</p:source>
	</p:match>
	
	<p:match pattern="swmonitoring/WML2/real-time/WSC/.*">
		<p:mime-type>text/html</p:mime-type>
		<!--  can have more -->
		<p:source>https://wateroffice.ec.gc.ca/report/real_time_e.html?stn=${p5?replace("WSC_","")}</p:source>
	</p:match>
	
	<p:match pattern="swmonitoring/WML2/real-time/WSC/.*">
		<p:mime-type>text/plain</p:mime-type>
		<!--  can have more -->
		<p:source>http://dd.weather.gc.ca/hydrometric/csv/QC/hourly/QC_${p5?replace("WSC_","")}_hourly_hydrometric.csv</p:source>
	</p:match>
	 
	 <!--  Meteo Service of Canada -->
	 
	 <p:match pattern="swmonitoring/WFS3/.*/WSC/.*">
		<p:mime-type>text/html</p:mime-type>
		<!--  can have more -->
		<p:source>http://geo.weather.gc.ca/geomet/features/collections/${p3}/items?STATION_NUMBER=${p5?replace("WSC_","")}&amp;f=html</p:source>
	</p:match>

	 <p:match pattern="swmonitoring/WFS3/.*/WSC/.*">
		<p:mime-type>application/vnd.geo+json</p:mime-type>
		<!--  can have more -->
		<p:source>http://geo.weather.gc.ca/geomet/features/collections/${p3}/items?STATION_NUMBER=${p5?replace("WSC_","")}&amp;f=json</p:source>
	</p:match>
	

	
	

	
</p:data>
