=== ksonda/usgs-sta-pygeoapi/chyld-pilot/schemas/DynamicTemplates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 sp1 (x64) (http://www.altova.com) by Eric Boisvert (Natural Resources Canada) -->
<xs:schema xmlns="urn:x-gsip:1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:x-gsip:1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Templates" type="TemplatesType">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="TemplatesType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="template" type="TemplateType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TemplateType">
		<xs:attribute name="pattern" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="template" type="xs:string" use="required"/>
		<xs:attribute name="requiresEntry" type="xs:boolean" default="true"/>
	</xs:complexType>
</xs:schema>

=== ksonda/usgs-sta-pygeoapi/chyld-pilot/dynamic/conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Templates xmlns:p="urn:x-gsip:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:x-gsip:1.0 ../schemas/DynamicTemplates.xsd ">
  <p:template name="wells" pattern="^https?://.*/id/waterwells/.*$" template="waterwell.ftl" requiresEntry="false"/>
 <p:template name="waterbody" pattern="^https?://.*/id/up_watershed/.*$" template="watershed.ftl" requiresEntry="false"/>
  <p:template name="watershed" pattern="^https?://.*/id/waterbody/.*$" template="waterbody.ftl" requiresEntry="false"/>
  <p:template name="catchment" pattern="^https?://.*/id/catchment/.*$" template="catchment.ftl" requiresEntry="false"/>
  <p:template name="swmonitoringq" pattern="^https?://.*/id/swmonitoring/MDDELCC.*$" template="swmonitoringq.ftl" requiresEntry="false"/>
  <p:template name="swmonitoringf" pattern="^https?://.*/id/swmonitoring/WSC.*$" template="swmonitoringf.ftl" requiresEntry="false"/>
  <p:template name="wellcatch" pattern="^https?://.*/id/featureCollection/wellsIn.*$" template="wellcatch.ftl" requiresEntry="false"/>
  <p:template name="aquifer" pattern="^https?://.*/id/hydrogeounits/.*$" template="aquifer.ftl" requiresEntry="false"/>
  <p:template name="dataset" pattern="^https?://.*/id/dataset/gin-.*$" template="gin_dataset.ftl" requiresEntry="false"/>
   <p:template name="mapunit" pattern="^https?://.*/id/mapunit/.*$" template="bedrock.ftl" requiresEntry="false"/>
</p:Templates>
